import { UniversalSkillManifest } from '../manifests/types.js';
import { normalizeSkillManifest } from '../manifests/validator.js';
import { SkillSecurityScanner } from '../security/security-scanner.js';
import { SkillTestRunner } from '../testing/test-runner.js';
import { SkillRegistry } from '../registry/skill-registry.js';

export interface SkillGenerationRequest {
  name: string;
  description: string;
  category?: string;
  capabilities?: string[];
  tools?: string[];
  permissions?: {
    network?: boolean;
    filesystemRead?: boolean;
    filesystemWrite?: boolean;
  };
}

export interface SkillGenerationResult {
  success: boolean;
  skill?: UniversalSkillManifest;
  files: Record<string, string>;
  scanPassed: boolean;
  testsPassed: boolean;
  error?: string;
}

export class SkillGenerator {
  private static instance: SkillGenerator;
  private scanner: SkillSecurityScanner;
  private testRunner: SkillTestRunner;
  private registry: SkillRegistry;

  constructor() {
    this.scanner = SkillSecurityScanner.getInstance();
    this.testRunner = SkillTestRunner.getInstance();
    this.registry = SkillRegistry.getInstance();
  }

  public static getInstance(): SkillGenerator {
    if (!SkillGenerator.instance) {
      SkillGenerator.instance = new SkillGenerator();
    }
    return SkillGenerator.instance;
  }

  /**
   * Generates a new skill bundle starting in UNVERIFIED state.
   */
  public async generateSkill(req: SkillGenerationRequest): Promise<SkillGenerationResult> {
    const skillId = req.name.toLowerCase().replace(/[^a-z0-9-_]/g, '-');

    const rawManifest: Record<string, any> = {
      id: skillId,
      name: req.name,
      version: '0.1.0',
      description: req.description,
      categories: [req.category || 'Custom'],
      capabilities: req.capabilities || [skillId.replace(/-/g, '_')],
      tools: req.tools || [`${skillId}.run`],
      source: 'private',
      publisher: {
        name: 'Hikmah Skill Generator',
        type: 'user',
        verified: false,
      },
      permissions: {
        network: { enabled: Boolean(req.permissions?.network), allowedDomains: [] },
        filesystem: {
          read: req.permissions?.filesystemRead ? ['./sandbox'] : [],
          write: req.permissions?.filesystemWrite ? ['./sandbox/out'] : [],
          tempOnly: true,
        },
        shell: { enabled: false, subprocess: false },
        credentials: { required: false, providers: [] },
      },
      runtime: {
        type: 'node',
        entrypoint: 'index.js',
      },
      isGenerated: true,
      certification: 'UNVERIFIED',
      state: 'DISCOVERED',
      enabled: false,
    };

    const manifest = normalizeSkillManifest(rawManifest);

    // Generate bundle files
    const skillMd = `# ${manifest.name}

> Generated by Hikmah Skill Generator
> Version: ${manifest.version} | State: ${manifest.state}

## Description
${manifest.description}

## Capabilities
${manifest.capabilities.map(c => `- \`${c}\``).join('\n')}

## Tools Exposed
${manifest.tools.map(t => `- \`${t}\``).join('\n')}
`;

    const indexJs = `/**
 * Implementation entrypoint for skill: ${manifest.name}
 */
export async function run(inputs, context) {
  console.log('Executing generated skill:', '${manifest.name}');
  return {
    status: 'success',
    timestamp: new Date().toISOString(),
    output: 'Execution completed safely.'
  };
}
`;

    const files: Record<string, string> = {
      'SKILL.md': skillMd,
      'index.js': indexJs,
      'manifest.json': JSON.stringify(manifest, null, 2),
    };

    // 1. Run Security Scanner
    const scanResult = await this.scanner.scanSkill(manifest, files);
    const scanPassed = scanResult.passed;

    // 2. Run Pre-flight Tests in Sandbox
    const testReport = await this.testRunner.runTests(manifest);
    const testsPassed = testReport.allPassed;

    if (scanPassed && testsPassed) {
      manifest.certification = 'SCANNED';
      manifest.state = 'VALIDATED';
    }

    // Register into private marketplace catalog
    this.registry.registerAvailableSkill(manifest);

    return {
      success: true,
      skill: manifest,
      files,
      scanPassed,
      testsPassed,
    };
  }
}
